$schema: https://schema.management.azure.com/schemas/2023-10-01/EnvironmentDefinition.json
name: dev-platform
summary: DEV platform baseline (aggregated resources)
description: Deploys the DEV environment as a single atomic environment via Azure Deployment Environments.
runner: azureDevCenter
# Parent template is in the same folder:
templatePath: ./main.bicep
parameters:
  - id: environmentType
    type: string
    displayName: Environment type
    description: Must match a Dev Center Environment Type (e.g., DEV/QA1/PROD).
    required: true
    default: DEV
  - id: location
    type: string
    displayName: Azure region
    required: true
    default: eastus
  - id: sqlAdminLogin
    type: string
    displayName: SQL administrator login
    description: Login name used for the SQL Server administrator account.
    required: true
  - id: sqlAdminPassword
    type: string
    displayName: SQL administrator password
    description: Password used for the SQL Server administrator account.
    required: true
    secret: true
  - id: stripeSecretKey
    type: string
    displayName: Stripe secret key
    description: Secret key injected into the Key Vault (SQLCONN, Stripe, and storage secrets are required).
    required: true
    secret: true
  - id: stripePublicKey
    type: string
    displayName: Stripe publishable key
    required: true
  - id: stripePriceId
    type: string
    displayName: Stripe price identifier
    required: true
  - id: stripeWebhookSecret
    type: string
    displayName: Stripe webhook secret
    required: true
    secret: true
  - id: b2cTenant
    type: string
    displayName: Entra External ID tenant name
    required: true
  - id: b2cClientId
    type: string
    displayName: Entra External ID client ID
    required: true
  - id: b2cSignInPolicy
    type: string
    displayName: Entra External ID sign-in policy
    required: true
  - id: storageConnectionString
    type: string
    displayName: Storage connection string
    description: Connection string stored in the Key Vault as STORAGE_CONNECTION.
    required: true
    secret: true
  - id: staticWebAppRepositoryUrl
    type: string
    displayName: Static Web App repository URL
    description: Git repository that hosts the Practx.io Static Web App source.
    required: true
  - id: staticWebAppRepositoryBranch
    type: string
    displayName: Static Web App repository branch
    description: Branch used for the Static Web App continuous deployment connection.
    required: true
    default: main
  - id: staticWebAppRepositoryToken
    type: string
    displayName: Static Web App repository token
    description: Optional token that authorises the Static Web App repository connection.
    secret: true
