name: Build Contracts

on:
  push:
    paths:
      - 'practx-contracts/**'
      - 'github/workflows/build-contracts.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Spectral
        run: npm install --global @stoplight/spectral-cli
      - name: Lint OpenAPI specs
        run: spectral lint practx-contracts/openapi/**/openapi.yaml -r practx-contracts/policies/spectral.yaml
      - name: Verify ODCS placeholders
        run: test -d practx-contracts/odcs
