name: Build Shared JS Workspace

on:
  push:
    paths:
      - 'practx-shared-js/**'
      - 'github/workflows/build-shared-js.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install --prefix practx-shared-js
      - name: Build workspace
        run: npm run build --prefix practx-shared-js
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: practx-shared-js
          path: practx-shared-js/packages/*/dist
