name: Deploy API Management

on:
  workflow_dispatch:
    inputs:
      apim_name:
        description: APIM instance name
        required: true
      env:
        description: Environment short name
        required: true
      resource_group:
        description: Target resource group
        required: true
      location:
        description: Azure location
        required: true
      publisher_email:
        description: Publisher email address
        required: true
      publisher_name:
        description: Publisher display name
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      - name: Bicep build validation
        run: az bicep build --file infra/modules/apim/apim.bicep
      - name: Deploy APIM
        run: |
          az deployment group create \
            --resource-group ${{ inputs.resource_group }} \
            --template-file infra/modules/apim/apim.bicep \
            --parameters apimName=${{ inputs.apim_name }} env=${{ inputs.env }} publisherEmail=${{ inputs.publisher_email }} publisherName="${{ inputs.publisher_name }}" location=${{ inputs.location }}
      - name: Import OpenAPI definitions
        run: |
          ./practx-apim/import.sh ${{ inputs.apim_name }} ${{ inputs.resource_group }}
