openapi: 3.0.3
info:
  title: Practx Service API
  version: 0.1.0
paths:
  /healthz:
    get:
      summary: Service health probe
      tags:
        - Diagnostics
      responses:
        '200':
          description: The service is healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
  /version:
    get:
      summary: Service version information
      tags:
        - Diagnostics
      responses:
        '200':
          description: The current deployed version.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: 0.1.0
