# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json


name: practx-keyvault
summary: Deploys an Azure Key Vault pre-populated with Practx.io application secrets.
description: |
  Creates an Azure Key Vault secured with RBAC authorization and seeds it with the application secrets
  required by Practx.io services. Supply the application secrets as parameters so dependent services can
  retrieve them by name after deployment.

runner: Bicep
templatePath: main.bicep

parameters:
  - id: environmentType
    name: Environment type
    type: string
    description: Dev Center environment type this deployment is for.
    required: true
    allowed:
      - DEV
      - QA1
      - PROD

  - id: location
    name: Azure region
    type: string
    description: Azure region used to deploy the environment resources.
    default: westus2

  - id: baseName
    name: Resource base name
    type: string
    description: Base name combined with the environment type to create resource names.
    default: practx

  - id: sqlConnectionString
    name: SQL connection string
    type: string
    description: Connection string seeded into the SQLCONN secret.
    required: true

  - id: stripeSecretKey
    name: Stripe secret key
    type: string
    description: Secret key for Stripe API calls.
    required: true

  - id: stripePublicKey
    name: Stripe publishable key
    type: string
    description: Publishable key for Stripe client integrations.
    required: true

  - id: stripePriceId
    name: Stripe price identifier
    type: string
    description: Price ID referenced by billing workflows.
    required: true

  - id: stripeWebhookSecret
    name: Stripe webhook signing secret
    type: string
    description: Secret used to validate Stripe webhook signatures.
    required: true

  - id: b2cTenant
    name: Entra External ID (B2C) tenant name
    type: string
    description: Name of the Entra External ID tenant used for authentication.
    required: true

  - id: b2cClientId
    name: Entra External ID (B2C) client ID
    type: string
    description: Client application ID for Entra External ID authentication.
    required: true

  - id: b2cSignInPolicy
    name: Entra External ID (B2C) sign-in policy
    type: string
    description: User flow or custom policy identifier for sign-in.
    required: true

  - id: storageConnectionString
    name: Storage connection string
    type: string
    description: Connection string stored as STORAGE_CONNECTION.
    required: true
