# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json

name: practx-staticwebapp
summary: Deploys the Practx.io Azure Static Web App and links it to the marketing repository.
description: |
  Provisions an Azure Static Web App (Free tier) that hosts the Practx.io marketing site and
  connects it to a Git repository for continuous deployment. The static site is configured
  to serve the frontend from the `frontend` directory and its Azure Functions API from the `api`
  directory.

runner: Bicep
templatePath: main.bicep

parameters:
  - id: environmentType
    name: Environment type
    type: string
    description: Dev Center environment type this deployment targets.
    required: true
    allowed:
      - DEV
      - QA1
      - PROD

  - id: location
    name: Azure region
    type: string
    description: Azure region where the Static Web App will be created.
    default: eastus2

  - id: baseName
    name: Resource base name
    type: string
    description: Base name that combines with the environment type to generate resource names.
    default: practx

  - id: repositoryUrl
    name: Repository URL
    type: string
    description: Git repository that contains the Practx.io static web application source.
    required: true

  - id: repositoryBranch
    name: Repository branch
    type: string
    description: Branch that should trigger deployments for the Static Web App.
    default: main

  - id: repositoryToken
    name: Repository token
    type: string
    description: Optional GitHub or Azure DevOps token that authorises CI/CD integration for the Static Web App.
    secret: true

  - id: appLocation
    name: App location
    type: string
    description: Path to the frontend source relative to the repository root.
    default: frontend

  - id: apiLocation
    name: API location
    type: string
    description: Path to the Azure Functions API relative to the repository root.
    default: api

  - id: outputLocation
    name: Output location
    type: string
    description: Build output path relative to the app location. Leave empty if the app is pre-built.
    default: ""
