# Azure DevOps pipeline to build and deploy the Practx Static Web App
# Required variables (variable group `Practx-SWA` recommended):
#   AZURE_STATIC_WEB_APPS_API_TOKEN - deployment token from the Static Web App
#   APP_LOCATION - optional override for frontend path (defaults to practx-swa/frontend)
#   API_LOCATION - optional override for API path (defaults to practx-swa/api)

# trigger:
#   branches:
#     include:
#       - main
#   paths:
#     include:
#       - practx-swa/*
#       - pipelines/practx-swa-azure-pipelines.yml

# variables:
#   - group: Practx-SWA
#   - name: APP_LOCATION
#     value: 'practx-swa/frontend'
#   - name: API_LOCATION
#     value: 'practx-swa/api'

# stages:
#   - stage: BuildAndDeploy
#     displayName: Build and deploy Static Web App
#     jobs:
#       - job: DeploySWA
#         displayName: Deploy Practx Static Web App
#         pool:
#           vmImage: 'ubuntu-latest'
#         steps:
#           - checkout: self
#             clean: true
#           - task: NodeTool@0
#             displayName: Use Node.js 18.x
#             inputs:
#               versionSpec: '18.x'
#           - script: npm install --prefix $(API_LOCATION)
#             displayName: Install API dependencies
#           - task: AzureStaticWebApp@0
#             displayName: Deploy to Azure Static Web Apps
#             inputs:
#               app_location: $(APP_LOCATION)
#               api_location: $(API_LOCATION)
#               skip_app_build: true
#               azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
