# Azure DevOps pipeline for provisioning Practx infrastructure with Bicep
# Configure the following variable group or pipeline variables before running:
#   AZURE_SERVICE_CONNECTION - name of service connection with contributor rights
#   AZ_RESOURCE_GROUP - target resource group for the deployment
#   AZ_LOCATION - Azure region for resources (must be westus2)
#   NAME_PREFIX - prefix used for resource names (e.g., practx)
#   TENANT_ID - Azure AD tenant id used for Key Vault access policies
#   FUNCTION_SKU - optional Functions plan SKU (default Y1)
# Optionally link a variable group named `Practx-Infra` that defines the variables above.

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*
      - pipelines/practx-infra-azure-pipelines.yml

variables:
  - group: Practx-Infra
  - name: AZ_LOCATION
    value: 'westus2'
  - name: FUNCTION_SKU
    value: 'Y1'

stages:
  - stage: Validate
    displayName: Validate Bicep deployment
    jobs:
      - job: WhatIf
        displayName: Run what-if validation
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Azure CLI what-if
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail
                az deployment group what-if \
                  --resource-group "$(AZ_RESOURCE_GROUP)" \
                  --template-file infra/bicep/main.bicep \
                  --parameters \
                    namePrefix="$(NAME_PREFIX)" \
                    tenantId="$(TENANT_ID)" \
                    location="$(AZ_LOCATION)" \
                    functionSku="$(FUNCTION_SKU)"

  - stage: Deploy
    displayName: Deploy infrastructure
    dependsOn: Validate
    condition: succeeded()
    jobs:
      - deployment: DeployBicep
        displayName: Deploy Bicep template
        environment: practx-infrastructure
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: Deploy resources
                  inputs:
                    azureSubscription: $(AZURE_SERVICE_CONNECTION)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -euo pipefail
                      az deployment group create \
                        --resource-group "$(AZ_RESOURCE_GROUP)" \
                        --template-file infra/bicep/main.bicep \
                        --parameters \
                          namePrefix="$(NAME_PREFIX)" \
                          tenantId="$(TENANT_ID)" \
                          location="$(AZ_LOCATION)" \
                          functionSku="$(FUNCTION_SKU)"
