trigger:
  branches:
    include:
      - main
  paths:
    include:
      - apps/woo-practx-payments/*
      - pipelines/woo-plugin-build.yml

stages:
  - stage: Package
    displayName: Package Woo plugin
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            clean: true
          - task: CopyFiles@2
            displayName: Stage plugin files
            inputs:
              SourceFolder: 'apps/woo-practx-payments'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/woo-practx-payments'
              Contents: |
                **
                !**/.git/**
                !**/.DS_Store
          - task: ArchiveFiles@2
            displayName: Create plugin zip
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/woo-practx-payments'
              includeRootFolder: true
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/woo-practx-payments.zip'
          - publish: $(Build.ArtifactStagingDirectory)/woo-practx-payments.zip
            artifact: woo-practx-payments

  - stage: Deploy
    displayName: Optional WordPress deploy
    dependsOn: Package
    condition: and(succeeded(), ne(variables['WP_DEPLOY_ENABLED'], 'false'))
    jobs:
      - job: SftpDeploy
        displayName: Publish over SFTP
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: current
            artifact: woo-practx-payments
          - script: |
              echo "Skipping deploy. Configure SCP/SFTP command here when ready."
            displayName: Placeholder deploy step
