# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json

name: practx-appservice
summary: Deploys a Linux App Service plan hosting the Practx.io web and API applications.
description: |
  Creates a Premium v3 Linux App Service plan along with paired web and API applications configured for
  Practx.io. The apps are wired to Application Insights and retrieve secrets from an existing Key Vault
  using system-assigned managed identities.

runner: Bicep
templatePath: main.bicep

parameters:
  - id: environmentType
    name: Environment type
    type: string
    description: Dev Center environment type this deployment is for.
    required: true
    allowed:
      - DEV
      - QA1
      - PROD

  - id: location
    name: Azure region
    type: string
    description: Azure region used to deploy the environment resources.
    default: westus2

  - id: baseName
    name: Resource base name
    type: string
    description: Base name combined with the environment type to create resource names.
    default: practx

  - id: keyVaultId
    name: Key Vault resource ID
    type: string
    description: Resource ID for the Key Vault that stores application secrets.
    required: true

  - id: keyVaultName
    name: Key Vault name
    type: string
    description: Name of the Key Vault that stores application secrets.
    required: true

  - id: appInsightsConnectionString
    name: Application Insights connection string
    type: string
    description: Connection string used to emit telemetry.
    required: true
    secure: true
