trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: Bash@3
    displayName: Validate Bicep templates
    inputs:
      targetType: inline
      script: |
        set -euo pipefail
        az bicep install
        files=$(git ls-files '*.bicep')
        if [ -z "$files" ]; then
          echo 'No Bicep files detected.'
          exit 0
        fi

        for file in $files; do
          echo "Validating $file"
          az bicep build --file "$file"
        done
