name: Validate Bicep templates

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bicep CLI
        run: az bicep install

      - name: Build all Bicep files
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t bicep_files < <(git ls-files '*.bicep')
          if [ ${#bicep_files[@]} -eq 0 ]; then
            echo 'No Bicep files detected.'
            exit 0
          fi

          for file in "${bicep_files[@]}"; do
            echo "\nValidating ${file}"
            az bicep build --file "$file"
          done
