name: Sync Dev Center catalog

on:
  push:
    branches:
      - main
    paths:
      - 'Environments/**'
      - '.github/workflows/devcenter-catalog-sync.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }},
          tenant-id: ${{ vars.AZURE_TENANT_ID }},
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          
      - name: Ensure Dev Center CLI extension is installed
        env:
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        run: |
          az extension add --name devcenter --upgrade
          if [ -n "$AZURE_SUBSCRIPTION_ID" ]; then
            az account set --subscription "$AZURE_SUBSCRIPTION_ID"
          fi

      - name: Sync catalog
        env:
          AZURE_DEV_CENTER_RG: ${{ vars.AZURE_DEV_CENTER_RG }}
          AZURE_DEV_CENTER_NAME: ${{ vars.AZURE_DEV_CENTER }}
          AZURE_DEV_CENTER_CATALOG_NAME: ${{ vars.AZURE_CATALOG }}
        run: |
          az devcenter admin catalog sync \
            --name "$AZURE_DEV_CENTER_CATALOG_NAME" \
            --resource-group "$AZURE_DEV_CENTER_RG" \
            --dev-center-name "$AZURE_DEV_CENTER_NAME"
