name: infra-sql

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'infra/modules/sql.bicep'
      - '.github/workflows/infra-sql.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    environment: DEV
    runs-on: ubuntu-latest
    env:
      RG: ${{ vars.CICD_RG }}
      LOCATION: ${{ vars.AZURE_LOCATION || 'westus2' }}
      NAME_PREFIX: ${{ vars.NAME_PREFIX }}
      SQL_ADMIN_LOGIN: ${{ secrets.SQL_ADMIN_LOGIN || '' }}
      SQL_ADMIN_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD || '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Ensure required variables
        run: |
          set -euo pipefail
          if [ -z "${NAME_PREFIX}" ]; then
            echo '::error title=Missing NAME_PREFIX::Define the NAME_PREFIX repository variable before running this workflow.'
            exit 1
          fi
          if [ -z "${SQL_ADMIN_LOGIN}" ] || [ -z "${SQL_ADMIN_PASSWORD}" ]; then
            echo '::error title=Missing SQL credentials::Set the SQL_ADMIN_LOGIN and SQL_ADMIN_PASSWORD repository secrets before running this workflow.'
            exit 1
          fi

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure SQL
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RG }}
          template: ./infra/modules/sql.bicep
          parameters: |
            location=${{ env.LOCATION }}
            namePrefix=${{ env.NAME_PREFIX }}
            adminLogin=${{ env.SQL_ADMIN_LOGIN }}
            adminPassword=${{ env.SQL_ADMIN_PASSWORD }}
