name: infra-storage

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'infra/modules/storage.bicep'
      - '.github/workflows/infra-storage.yml'

permissions:
  id-token: write   # required for azure/login OIDC
  contents: read

jobs:
  deploy:
    environment: DEV
    runs-on: ubuntu-latest
    env:
      RG: ${{ vars.CICD_RG }}
      LOCATION: westus2
      SA_PREFIX: sto-practx   # will be normalized (dashes removed) in the script
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Storage Account
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ vars.CICD_RG }}
          template: ./azuredeploy.json
          parameters: 'storageAccountName=stodevpractx${{ github.run_number }}'
