name: infra-storage
on:
  workflow_dispatch:
    inputs:
      swa_csv:
        description: "Comma-separated SWA resource names (e.g., practx-swa)"
        required: true
        default: "practx-swa"
  push:
    branches: [ main ]
    paths:
      - 'infra/modules/storage.bicep'
      - '.github/workflows/infra-storage.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG: your-resource-group
      LOCATION: westus2
      SA_PREFIX: prx # used to build unique storage names
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Loop SWAs and deploy storage + app settings
        shell: bash
        run: |
          IFS=',' read -ra SWAS <<< "${{ github.event.inputs.swa_csv }}"
          for SWA in "${SWAS[@]}"; do
            SWA_TRIM=$(echo "$SWA" | xargs)
            # Build a globally-unique storage account name: <prefix><swa><rand> (<=24, lowercase)
            RAND=$(tr -dc a-z0-9 </dev/urandom | head -c 5)
            BASENAME=$(echo "${SWA_TRIM//-/}" | tr '[:upper:]' '[:lower:]' | cut -c -12)
            SA_NAME="${SA_PREFIX}${BASENAME}${RAND}"

            echo "==> Deploying storage for SWA: $SWA_TRIM  as SA: $SA_NAME"

            az deployment group create \
              --resource-group "$RG" \
              --template-file infra/modules/storage.bicep \
              --parameters location="$LOCATION" storageAccountName="$SA_NAME" \
              --query properties.outputs

            # Fetch connection string & blob endpoint
            CONN=$(az storage account show-connection-string -g "$RG" -n "$SA_NAME" --query connectionString -o tsv)
            ENDPOINT=$(az storage account show -g "$RG" -n "$SA_NAME" --query "primaryEndpoints.blob" -o tsv)

            # Set SWA app settings (creates/updates)
            az staticwebapp appsettings set -g "$RG" -n "$SWA_TRIM" --setting-names \
              BLOB_CONNECTION="$CONN" \
              BLOB_ENDPOINT="$ENDPOINT" \
              CONTAINER_LANDING="landing" \
              CONTAINER_PRACTICE="practice" \
              CONTAINER_PATIENT="patient" \
              CONTAINER_EQUIPMENT="equipment" \
              CONTAINER_SERVICE="service"

            echo "Configured app settings for $SWA_TRIM"
          done
